# Generated by Django 4.0.2 on 2022-04-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
